### ISSUE TITLE
KeyError: 'conversations'

### ISSUE THREAD

**Issue by dg4u** [AllenBurgett/hangouts_takeout_to_backupandrestore#16] opened 2022-11-05 18:54 UTC
Your program seemed very promising, but when I downloaded and ran it as instructed, I got the following error message:

line 300, in main
for thread in data['conversations']:
KeyError: 'conversations'
 
I don't know what this means or how to fix the program.

**Comment by AllenBurgett** [comment] 2022-11-06 23:15
That is where all of the messages should be stored. I just pulled a new Hangouts.json from Takeouts and it's still showing the same data layout. The beginning of your Hangouts.json file should look like the following:
![image](https://user-images.githubusercontent.com/12436387/200200562-11abdcb3-6318-48b2-a9ec-6c4cd8e2e64b.png)

If it doesn't, there may be an issue with your Hangouts.json. How big is your file? Mind telling me what the first 5 lines of your Hangouts.json file looks like?

**Comment by dg4u** [comment] 2022-11-07 04:56
Thanks for helping me out, Allen!

I have four Takeouts Hangouts.json files: one each from the years 2015, 2017, 2019, and 2022. The first two years (the oldest) have a different structure than the two most recent. They do not even contain the word "conversations" anywhere at all! 

Here is how they look:
![image](https://user-images.githubusercontent.com/13475450/200226853-48435cd4-2cc3-45a9-b29a-94e853dd500a.png)

![image](https://user-images.githubusercontent.com/13475450/200227753-4ebecfe8-6567-41dc-a86a-f5c61526267f.png)

Yes, that is the beginning of the two Hangouts.json files from 2015 and 2017.

I ran jsontoxml.py on all four, but only the 2019 file converted correctly. I confirmed this by uploading the test.xml file to https://www.synctech.com.au/sms-backup-restore/view-backup/ 

The 2015 and 2017 Hangouts.json files produced the error message I reported above: "KeyError: 'conversations'"

And the 2022 Hangouts.json file generated no errors but produced only one line of output in text.xml:
`<smses count="0" backup_set="145bea68-a1f4-4068-a631-06757067e675" backup_date="1667793041683" />`
Even though this Hangouts.json file appears to be a well structured, and it has a file size of of 337 kB, and I can read lots of actual text messages when I look inside it.

**Comment by AllenBurgett** [comment] 2022-11-07 05:31
Interesting. I wouldn't have a data set (or probably time) to build in support for the older two sets. However, I'd like to get your 2022 set working. I haven't used Hangouts in awhile now, but hopefully if they've changed something it's reflected in the data set I just pulled. If not, I might have a few questions about how your 2022 set is structured. I'll try to work on this a bit tomorrow.

**Comment by AllenBurgett** [comment] 2022-11-07 05:38
An initial question about your data. Does the 2022 file contain any of the following:
segment
phone_number
i18n_data
gaia_id

**Comment by dg4u** [comment] 2022-11-07 05:49
segment = 220
phone_number = 0
i18n_data = 0
gaia_id = 572

**Comment by AllenBurgett** [comment] 2022-11-07 21:30
@dg4u, so I've reviewed my latest Hangouts.json from Takeout. I have not been able to find any messages in that export that are actually SMS/MMS messages. Seems like Google may have purged all of that content from their Hangouts export recently (googling around, sounds like Hangouts was deprecated on Nov 1st of 2022). When I log in to Hangouts now, I no longer see any of my old SMS/MMS messages, which seems to support that theory. Do you have a recent export from before Nov 1st (I'm not sure when they purged that data)?

**Comment by dg4u** [comment] 2022-11-08 00:01
When I go to Hangouts on the web ( https://hangouts.google.com/ ) it still shows all of my messages. They are also available at new Chat website ( https://mail.google.com/chat/u/0/#chat/welcome ). My understanding is that the hangouts service will be shut down permanently and all of the data deleted on 2023 January 1. See https://support.google.com/chat/answer/9854901

As to the Google Takeout Hangouts.json files, the one I downloaded on 2022-09-08 is essentially the same as the one I downloaded yesterday, 2022-11-06. There's a minor difference in file size but I cannot find any differences in the actual text they contain. Both of these json files, by the way, produce the exact same single line of output in text.xml ( "smses count = 0" that I shared with you previously ) when run through jsontoxml.py.

What I think happened sometime in 2019 is that the Hangouts messages, which were linked to people's phone numbers, became linked to people's Google IDs. That's why the phone_number tag no longer shows up in my recent Hangouts.json files, even though there are many text messages clearly visible in the files. 

I wonder if some of the messages in the older 2019 Hangouts.json files I have are also associated with people's Google IDs rather than their phone numbers? If so, it means that your program will skip them when it does the conversion, since it seems to be looking for the phone_number tag rather than the person's ID ( is that what gaia_id is? ) as an indicator/counter of conversations. When I got to the Google Hangouts or Chat website it clearly shows that there are 6 conversation with around 100 messages total, but your converter program reports seeing zero of them.

**Comment by AllenBurgett** [comment] 2022-11-08 00:29
@dg4u that's good information to have! So, if we're pretty confident that your data still has SMS/MMS messages in it, we might still be able to recover it. Since I don't have a working data set (my messages have been stripped from Hangouts it seems), I think there are two paths we can take:

1. Determine if/where they're storing the phone number. For that I would need the following:
  -  I would need you to search your data for a known phone number (I don't know how they're segmented, so try the whole thing/area code/last 4/etc) and send me over the what the data structure looks like in that area of the json (purge any sensitive data, but leave me a message about what it was and how it was structured).
  - Or you could grab an entire block of participant_data and events (this should be where information about the recipients and messages are stored respectively) is stored. Please scrub that of any sensitive data before sending it.
  
2. There is already an option to supply the '-p' flag when running the script. This allows you to add a number yourself for a given Google ID (the gaia_id) and the name is included. I believe when we added that functionality we made it per unlabeled (no found phone number) entry and we didn't attempt to save your entries off in any sort of lookup table (because it seemed like a one-off path at the time). I will implement a lookup table now to make that path a little more accessible. 

Let me know how you'd like to proceed with the rest of it.

**Comment by AllenBurgett** [comment] 2022-11-08 01:08
The lookup table seems like it might be a little tricky without knowing what the participant_data block of an actual text message looks like. I tried testing it with just Hangouts data and the result wasn't great. lol

**Comment by dg4u** [comment] 2022-11-08 01:25
I just tried running jsontoxml.py with the -p flag on the Hangouts.json that I download yesterday, and lo and behold, it reported finding 235 smses in the text.xml file! Unfortunately, I had to enter my own phone number multiple times. 

When I uploaded the text.xml file to https://www.synctech.com.au/sms-backup-restore/view-backup/ I could see that two conversations had been correctly linked to the person's name and phone numbers (which I entered) but the other 4 conversations (with different people) were all run together as one conversation with myself. 

What this means to me is that when your program was prompting me for the phone number of myself multiple times, it really wanted to know the phone number of each of these other people. Since I wouldn't even know which person it was asking about I could try entering different random phone numbers and see if it then splits them off into different conversations?

**Comment by AllenBurgett** [comment] 2022-11-08 01:46
Yeah, that's what it's doing. That's why I need to see see what that participant data looks like. Any luck on identifying if the json is storing numbers? Any chance you could send me over some redacted version of the participant_data block? I think in order for the -p option to work, I'm going to need to rework how it parses the participant_data section and I don't really have the data model to base any of that work off of. 

I'm really hoping they're still stashing the phone number somewhere and we can just figure out how they've rearranged the data.

**Comment by dg4u** [comment] 2022-11-08 02:34
I'm hoping that these are two of the participant_data blocks you wanted? There are 7 of them in the json file, which matches the number of conversations. 

This one is from a conversation that did not show the name of the person I was texting with.

![200460167-914098aa-6045-4594-8b16-31461772-new](https://user-images.githubusercontent.com/13475450/200464803-ae3877e4-c429-4252-a1e1-ddc13cc5bed2.png)

This participant_data block is from a conversation that did correctly show the person's name I was texting with.

![200460909-36de52bf-74b2-4c3d-99e0-13bb63bf-new](https://user-images.githubusercontent.com/13475450/200464873-c48ce9f7-f3da-499c-9b5c-f1ede5c44bea.png)

**Comment by AllenBurgett** [comment] 2022-11-08 03:07
Out of curiosity, are these both text message conversations? Neither of them are Hangouts conversations, right?

**Comment by dg4u** [comment] 2022-11-08 03:16
All of these messages are from Hangouts, which I used exclusively for all of my text messaging until 2019, at which time I was forced by Google (somehow, I don't remember exactly what changed) to switch to Google Messages. From 2019 on, I used Google Messages exclusively for all of my text messaging. Which I now backup with "SMS Backup and Restore", and that's why I want to convert all of those old Hangouts messages into the same backup archive format.

**Comment by dg4u** [comment] 2022-11-08 03:39
The classic Hangouts app on my Nexus 5X phone was able to sent and receive SMS and MMS text message to and from people who weren't using Hangouts. (This may have been possible only because I was using Google Fi as my cellular service.) But then Google updated the app so that it would only work with other Hangouts users. That's probably when I switched to using Google Messages. See https://support.google.com/fi/answer/9984024

**Comment by AllenBurgett** [comment] 2022-11-08 03:40
So, when you say these are Hangouts messages, you mean messages that are between two gmail accounts, not between two phone numbers or are you trying to transfer the old text messages from before the 2019 forced switch to messages?

**Comment by dg4u** [comment] 2022-11-08 03:53
Yes, all of the Hangouts messages that I am trying to transfer are from between 2015 to 2019. When I sent them on my phone it could have been via a phone number or a name in my contacts. Also I received SMS text messages from people who weren't in my contacts, and thus it just showed their phone numbers (SPAM messages, for example).

**Comment by AllenBurgett** [comment] 2022-11-08 03:55
You said you have an export from 2019. Would that export encapsulate all of the messages you're trying to extract or are you also trying to include newer messages that came from other Hangouts users?

**Comment by AllenBurgett** [comment] 2022-11-08 03:59
Ok nevermind, reading one of your previous messages, the 2019 one seems to be the one that you have gotten to work (which makes sense, that's when this project was created). So, it sounds like you're trying to import Hangouts messages, I'll define that here as a set of messages initiated between two users using their gmail accounts to connect and not a phone number via Google Fi. Is that a correct assertion?

**Comment by AllenBurgett** [comment] 2022-11-08 04:09
So, here are the things I'm still trying to figure out: 
> Yes, all of the Hangouts messages that I am trying to transfer are from between 2015 to 2019.

I thought above you had successfully imported these messages from an export from 2019?

> When I sent them on my phone it could have been via a phone number or a name in my contacts

When you say contacts here, does that always mean it was tied to a phone number (thus Hangouts sent it as a SMS message) or do you mean that some were via phone numbers (through Google Fi's SMS via Hangouts feature), but others were just from your Google Hangouts contacts, thus probably people who you could have talked with via Hangouts with or without Google Fi's SMS via Hangouts feature (I believe those contacts are usually connected via a gmail account)?

**Comment by dg4u** [comment] 2022-11-08 04:15
Sometime between 2019 when I stopped using Hangouts and a few weeks ago when Google sent me an email saying that all my Hangouts data was going to be deleted in January of 2023, all of the hundreds of conversation and roughly 19,000 messages disappeared from Hangouts/Chat except for these 7 conversation and roughly 100 messages that we've been talking about. When I run Takeout now that's all I get; when I ran Takeout in 2019 I got all 19,000 messages. 

What I don't know, and would like to figure out, is if one set is missing the other or if they are an overlap. All I really need is one complete set of all my Hangouts text messages. But at this point I'm not even sure if your converter is even seeing all of the messages in the larger 2019 json file, since it can't see all of the messages in my current smaller 2022 json file.

**Comment by AllenBurgett** [comment] 2022-11-08 04:24
Ok, I think I understand. So, the converter purposely skips over any message that it sees as a Hangouts only (no phone number) message. The export from 2019 would have converted any text messages (phone numbers). It seems like sometime between 2019 and now, Google purged all of those text messages out of their Hangouts export. I also had Google Fi and used Hangouts to send and receive text messages, which is why I built this converter. 

It's my understanding that all of those Hangouts conversations should automatically transfer over to Google Chats.

So, my next question is: lets assume that this program captured all of your text messages, and your Hangouts conversations are being transferred automatically over to Google Chats. Would there still be messages that you believe weren't captured in one of those two processes?

**Comment by dg4u** [comment] 2022-11-08 04:24
Yes, I believe that the text messages sent and received by me in Hangouts used a combination of phone number for SMS based messaging and Google IDs (based on whatever they were based on, at one time it was Google Plus profiles, which no longer works. See https://stackoverflow.com/questions/27028322/how-to-look-up-user-information-from-google-gaia-id ) for Hangouts data based messaging.

**Comment by dg4u** [comment] 2022-11-08 04:27
We have a one message lag in our responses, so I'm always answering your previous question when a new one comes in! LOL

**Comment by AllenBurgett** [comment] 2022-11-08 04:28
I'll let you catch up ;)

**Comment by dg4u** [comment] 2022-11-08 04:30
The supposed automatic conversion of my Hangouts data to Chats, that I was waiting to see happen before the system shut down, never did. Except for those 7 conversations that are currently available via Takeout and that your converter doesn't see.

**Comment by AllenBurgett** [comment] 2022-11-08 04:35
So, when I go to chats, I'm down to 8 conversations, as opposed my my Google Messages app, where I've got plenty more conversations. Those 8 conversations represent all the people I ever communicated with via Google Hangouts only (no phone number, just a backend Google connection, usually email). 

Is it possible that those 7 conversations you are referring to are Hangouts only messages and the only Hangouts only threads you created? Based on what I'm seeing on my end, I'm not seeing any of my old text messages, just my Hangouts only messages.

**Comment by dg4u** [comment] 2022-11-08 04:55
There was an option (apparently) with Google Fi (that I didn't find out about until last week when I started investigating what happened to all of my Hangouts text messages) that allowed you to convert all of your Hangouts messages to Messages messages. ( see https://support.google.com/fi/answer/9984024#retrieve_texts&zippy=%2Cstep-transfer-or-sync-your-text-messages ) This involved a special Google Fi configuration setting in the Messages app settings, which then downloaded all of the Hangouts data from the Fi servers and stuffed it into the SMS database on your phone. But it was turned off at the end of September in 2021 (I was a year and one month too late!) But perhaps you were able to complete this conversion so that all of your old Hangouts messages are now in the Google Messages app? 

To answer your question, I consider it unlikely that in four years of texting I only had 7 conversations with other Hangouts users, but I guess it's possible.

**Comment by dg4u** [comment] 2022-11-08 05:03
I'm not sure if this is useful information for you, but as I was looking up the meaning of gaia_id I came across this topic [How to look up user information from Google GAIA ID?](https://stackoverflow.com/questions/27028322/how-to-look-up-user-information-from-google-gaia-id) which, if you scroll down to answer 5, supposedly shows how to retrieve a person's information (which I assume would include their name) using the Google People API. Perhaps that could be used to by your converter to lookup the names of participants in a Hangout only conversation? But maybe it's too much work? I have no idea.

**Comment by AllenBurgett** [comment] 2022-11-08 05:12
So, I never used Google's tool. I converted all of my Google Fi SMS/MMS messages to Google Messages via this tool. I never transferred my Hangouts only messages, because I assumed they'd move on to whatever Google's next non-SMS messaging service would be. Which they seemed to, but I also so rarely used it that I wasn't too invested in keeping those particular messages if they went away. 

However, I've reworked the -p flag for one on one conversations. If you pull the new jsontoxml.py file, using the -p flag should give you better results. I haven't reworked the group messages part, but I wanted to give you something tonight that you could try. Let me know if that helps at all.

It's kinda crude, but it should work. If these are Hangouts only messages, it's going to insert them into your text message conversations with those people or if you use a dummy number, then I guess you'll have that record in Google Messages. 

I think I keep coming back to my original concern, though. It sounds like Google has purged some data. This program won't see data that Google's not currently showing you in their app. It might be worth opening a support ticket with Google to see if there's anything they can do to help you recover any potentially lost data.

**Comment by AllenBurgett** [comment] 2022-11-08 05:19
So, I played around with that API a little bit, but I think it's through Google's platform of tools and I'm not sure if I can use it without creating an App. I find their directions on utilizing their APIs in a non-test manner (in a way that I could share it with other people) to be a bit convoluted. That's probably a me problem, but if I needed to implement a solution involving that, the complexity would be a little higher than I think I'd be willing to bite off.

**Comment by dg4u** [comment] 2022-11-08 05:51
I just ran your updated program against my 7 conversation Hangouts.json. It completed without any errors, but the resulting text.xml file had two deficiencies when I uploaded it to https://www.synctech.com.au/sms-backup-restore/view-backup/

The first deficiency is that only 5 of the 7 conversations showed up (the first two were skipped) even though I was asked for phone numbers for all 7.

The second deficiency is that when I open any of the conversations, both the sender and receiver are shown as being the same name and phone number, not mine but the other participant's. Even though your program began by asking me to confirm my name, it never used that name as a participant in any of the conversations.

I hope that helps. I'm going to bed now.

**Comment by AllenBurgett** [comment] 2022-11-08 15:39
I don't believe the second one's a deficiency. In the left column of that view-backup page, you'll see 'Type'. You sent a message to that person or you received a message from that person. The script asks for you to confirm your ID so it can filter you out and focus on who the conversation is with, which is what Backup and Restore cares about. 

As for the first part, I'm not quite sure what would be happening there. When you say it asked for phone numbers for all 7, did it present a name with each one or were some (possibly 2) just Google IDs? I know in the participant_data blocks you shared above, one only had your name, but nothing in the second object but the gaia_id and chat_id. I'm not sure how Backup and Restore would handle taking a Nil value for a contact name. It might just choose to ignore those entries. Could you confirm this is what's happening? If so, I could add a prompt for a name.

**Comment by dg4u** [comment] 2022-11-08 16:30
I see what you mean about the second deficiency (that sender and receiver are the same when viewing the "SMS Backup and Restore" xml file). I confirmed that it does the same thing on the "good" conversion of the older (2019) Hangouts.json file. So I'm willing to let that "deficiency" go, as it was really just a deficiency in my expectations of how the results should look.

As to the first deficiency I mentioned (that two of the conversations in the json did not get converted to xml), here is what I am able to confirm by rerunning "jsontoxml.py -p": 
1. Your program correctly presented my name and gaia_id for confirmation (y/n).
2. The first two "Please provide the phone number" prompts displayed "None" for the Google user's name. And yes, being asked for a name at this point would be very helpful!
3. All the rest of the "Please provide the phone number" prompts did display a person's name. Note: for speed of testing and simplicity's sake, I've found that I can just enter one numeral for each of the phone numbers (consecutively 1,2,3,4,5,6,7) and that these will then show correctly when viewing the converted archive.
4. The results of the conversion show all of the conversations with people whose names existed in the json but omitted all of the people who did not have names associated with their gaia_ids in the Hangouts.json Takeout file.

**Comment by AllenBurgett** [comment] 2022-11-08 17:16
@dg4u I've added a prompt for the name. Please let me know if that works on your side. I don't have a data set to test that particular change against.

**Comment by dg4u** [comment] 2022-11-08 17:58
Your new code appears to work perfectly! All 7 conversations are now appearing in the text.xml file. I am extremely happy about this!

An interesting discovery: When I ran the new and improved conversion program with the -p option on the older (2019) Hangouts.json file, it found all 7 of the current (Hangouts only) conversations from the current (2022) Hangouts.json Takeout file along with the many SMS based conversations that we already knew existed in that archive. This makes me happy as well, because it means I won't have to combine the older and newer Takeout files in order to get a complete set of all my Hangouts conversations.

One problem though, which you may not have a good solution for, is that when I am prompted for the names and phone numbers of unidentified participants, I have no idea how to link the displayed gaia_id with a real person. So what I am doing is entering a dummy name, like "Person One" and "Person Two" on the first pass, so that I can look at the converted conversations and figure out who it was that I was texting with, and then on a second pass through the converter I am able to enter the actual names of the people whose gaia_id is presented (assuming I either remember their order of appearance or have assigned a sequential phone number (1,2,3,4 etc.) so that I can write down which person goes with which conversation). This is not an insurmountable problem, but I thought I'd mention the technique that I am using to overcome it for the benefit of future users of your conversion program who might run into the same issue.

**Comment by AllenBurgett** [comment] 2022-11-08 18:34
I'm glad it's working! 

There are probably some rather clunky ways to manage this, but it would mostly be manual intervention (the way you described is probably the most logical way to manage that). The core of the issue is that this program wasn't designed to handle those Hangouts only conversations. It was only intended to extract SMS (and the later MMS) messages from your Takeouts and put it into a format that could be imported into Google Messages. From there you could continue to have the text conversation you were having without the gap in message history. 

The Hangouts message handling was something novel and was never fleshed out. It's clunky at best and hard to improve upon, because it's doing something that isn't as straightforward as delivering a message, tied to a phone number, to an application to import into another application. 

Now that the days of SMS/MMS via Hangouts (and Hangouts itself it seems) is over, this project will be archived. Some of the json parsing might be helpful to someone in the future, but I don't expect this project to gain any additional features. 

Thank you for helping to get that one last bit into a working state!

**Closed as completed by AllenBurgett** 2022-11-08 18:34 UTC

**Comment by dg4u** [comment] 2022-11-08 19:14
Thank you Allen. I really appreciate the work you have put into this conversion program. I've already told other people about it and plan to mention it in the Hangouts community help forum run by Google.

However, I've encountered one new issue. After converting my older (2019) Hangouts.json Takeout archive, I noticed that many of the conversations show a phone number as the participant's name. What I mean by this is that the output looks like "+1234567890 (+1234567890)" rather than "Joe Blow (+1234567890)". Unfortunately, our conversion program does not prompt for the participant's name in these cases because the name field is not missing, it's just an exact duplicate of the phone_number field. What would be really helpful is if your program could check for this condition (name = phone_number) for each participant and then present a prompt to enter the person's name just like it does when the name field is missing altogether. It doesn't seem like this would be terribly difficult to implement; couldn't you just add one more condition to whatever triggers the "prompt for participant name" routine?

**Comment by AllenBurgett** [comment] 2022-11-08 19:47
I think my first question would be, are these real people you're having conversations with? My intuition suggests those are random messages that you've never saved a contact name to (like a delivery app telling you your food has been dropped off or FedEx telling you a package will be delivered tomorrow). This data is derived from an export of your configuration and contacts.

This would probably be somewhat straightforward to implement, but would also probably catch a decent amount more bad data, than it would resolve any good data. There's also the point that these conversations will still import and you'll have the entire conversation there in front of you, which would make it easier to determine who you're talking to and adjust the contact name at that time. The process of going and finding a number that's hopefully in your contacts list or if not trying to determine who the person is without the conversation in front of you, seems more daunting than resolving a handful of these conversations in your Messages inbox. Maybe that's just me. 

There's also the idea of how it could muddy the waters on import. If you have a legitimate contact, that since the export you've assigned contact information, and you now assign them a name here, you could end up with a duplicate contact entry (this is part of why -p wasn't fleshed out earlier).

I think there are a few too many caveats here for me to commit to introducing this change for a larger audience. You are however welcome to create a fork and add that change.

**Comment by dg4u** [comment] 2022-11-08 20:38
I hear you and will try to implement the "name = phone_number condition" myself. I know of no way to add these people's names after the conversion process has finished, in Messages, for example, as you suggested.

For what it's worth, I took a look at these unnamed conversations (there's about 60 of them) before writing you about the issue, and it turns out that most of them are meaningful conversations (that I want to keep) with people whose names I know but, for some reason, were never saved as part of the Takeout process.

I'll report back how I mange to solve this. If nothing else, I can use search and replace in the Hangouts.json file to replace phone numbers in the participant_name field with the actual names of the people I was conversing with. I'm pretty sure that your converter would then label these conversations correctly. But as you say, what will Google Messages do with duplicate contacts? I guess I'll find out. I may have to export everything from Messages (using SMS Backup and Restore), resolve the naming differences by editing and combining the xml files, and then import it all back into Google Messages. This could take a while. Smile.

**Comment by AllenBurgett** [comment] 2022-11-08 21:02
That's seems like quite a lot of conversations that Google dropped the ball on. I don't think I've ever encountered that issue nor have I heard it reported. That's pretty wild. 

However, in messages, you should be able click the hamburger menu at the top right and click "Add contact". I'll add pictures in a separate comment.

**Comment by AllenBurgett** [comment] 2022-11-08 21:02
![Screenshot_20221108-145935](https://user-images.githubusercontent.com/12436387/200674751-4130ae2d-a44f-4982-9c52-fb2fc668b8eb.png)
![Screenshot_20221108-150053](https://user-images.githubusercontent.com/12436387/200674772-348ad4c5-8acb-449f-98f0-b52305c57cc4.png)

**Comment by AllenBurgett** [comment] 2022-11-08 21:04
![Screenshot_20221108-150053~2](https://user-images.githubusercontent.com/12436387/200674990-1ae07ec8-4eee-4147-8c2c-daf15a3ecc54.png)
![Screenshot_20221108-150053](https://user-images.githubusercontent.com/12436387/200675004-bd0e72df-1ec1-44e2-93ff-749828ddac05.png)

**Comment by AllenBurgett** [comment] 2022-11-08 21:04
![Screenshot_20221108-150053~2](https://user-images.githubusercontent.com/12436387/200675108-4bf17cb7-8a8a-486e-b3ef-a3593c6fe388.png)
![Screenshot_20221108-145935](https://user-images.githubusercontent.com/12436387/200675117-3253985b-3cd8-4a55-b710-165cd79eb3c3.png)

**Comment by dg4u** [comment] 2022-11-08 21:34
I don't know what version of the Google Messages app you are using, but mine doesn't look like that. And it appears that you are simple adding a new contact to an existing conversation rather than renaming a contact from "+1234567890" to "Joe Blow".

**Comment by AllenBurgett** [comment] 2022-11-08 21:45
Ah, I see, you're saying that Backup and Restore is adding that number as the name for the chat. I would assume then that it created a contact in that case. Under "Details" I can edit the contacts. Not sure if your version has that. I would think there should be some menu for the individual chat, though.

I'm using the latest version on Android 13 on a Pixel. I've had this layout for awhile, though.

**Comment by dg4u** [comment] 2022-11-10 03:57
Hi Allen, I just wanted to report the progress I've made since we last communicated. 

I took all of the Hangouts.json files that I converted to "SMS Backup & Restore" xml files using your program and I restored them to my new Pixel 7 Pro phone (which only had a couple of text messages on it) using the "SMS Backup & Restore" app. Prior to this I was just viewing them online at https://www.synctech.com.au/sms-backup-restore/view-backup/ . I also restored two previous SMS backups I'd made (one recently and one years before) to the new phone using the "SMS Backup & Restore" app. 

Amazingly, they all sorted themselves out in the Google Messages app so that the SMS and Hangouts text messages now coexist in the same conversations. Most of the "phone number" named conversations were also converted to people's names automatically. For the few that didn't, I was able to create a new contact (like you tried to show me) using that phone number and then filling in the persons name in Google contacts. I now appear to have all of my text messages (since 2015) in one place!

The only problem I've encountered is that most of the pictures that were included in the various text messages are missing. It shows links to the online location where the pictures used to reside, but they apparently are no longer there. The links look something like this: https://lh3.googleusercontent.com/-sviyn624Ufk/UwZcDwHYRaI/AAAAAAAAAH8/dE56Hji1VzI2zJM6dB7YhzVjbJKXZKGyQCK8B/s0/25.Waving_640x442.gif

I can see which files the links were pointing to by the names displayed at the very end, "Waving_640x442.gif" in the example above, but I don't know where in my Google profile I would put these files or how to reestablish the links. They appear to be in a hidden album in Google Photos used just for SMS or Hangouts messages. If you click on the link above you will see the Photos logo in the browser tab. 

Many of the photos that are missing in the Messenger app still exist in my Google Photos library. I've read the each photo has a hidden URL that can be used to display it. I'm just not sure how to make that linkage happen.

Cheers,
Dexter
